Repository Brainrotlang/brainrot, pull requests merged in 2025-01, with the labels that each got.

#37 feat: gigachad keyword - handles double floating point types
  ast.c
  ast.h
  examples/circle_area_double.brainrot
  lang.l
  lang.y
  tests/expected_results.json
Labels: enhancement

#38 fix: output float double formatting
  ast.c
  examples/circle_area.brainrot
  tests/expected_results.json
Labels: bug

#39 refactor: change comment char to toilet emoji
  examples/circle_area.brainrot
  examples/circle_area_double.brainrot
  lang.l
Labels: refactor

#40 refactor: change edging keyword to edgy
  README.md
  docs/brainrot-user-guide.md
  docs/the-brainrot-programming-language.md
  examples/boolean.brainrot
  examples/fizz_buzz.brainrot
  examples/output_error.brainrot
  lang.l
  lang.y
Labels: refactor

#42 tests: add more edge cases
  ast.c
  examples/comparison_edge_case.brainrot
  examples/division_edge_cases.brainrot
  examples/double_vs_float.brainrot
  examples/float_precision.brainrot
  examples/integer_overflow.brainrot
  examples/mixed_types.brainrot
  examples/modulo_edge_case.brainrot
  examples/scientific_notation.brainrot
  examples/type_conversion.brainrot
  examples/unsigned_integer_wrap.brainrot
  lang.l
  tests/expected_results.json
  tests/test_brainrot.py
Labels: tests

#49 feat: add builtin function ragequit
  README.md
  ast.c
  ast.h
  docs/brainrot-user-guide.md
  docs/the-brainrot-programming-language.md
  examples/rage_quit.brainrot
  lang.y
Labels: enhancement

#51 refactor: added var_type enum
  ast.c
  ast.h
  examples/boolean.brainrot
  lang.y
  tests/expected_results.json
Labels: refactor

#55 feat: smol keyword - short integer variable
  README.md
  ast.c
  ast.h
  docs/the-brainrot-programming-language.md
  examples/sizeof.brainrot
  lang.l
  lang.y
  tests/expected_results.json
Labels: enhancement

#56 feat: deadass keyword for const modifier
  .github/workflows/ci.yml
  README.md
  ast.c
  ast.h
  docs/the-brainrot-programming-language.md
  examples/const.brainrot
  lang.l
  lang.y
  tests/expected_results.json
  tests/test_brainrot.py
Labels: enhancement

#63 Update ci.yml
  .github/workflows/ci.yml
Labels: CI

#64 ci: remove run examples step
  .github/workflows/ci.yml
Labels: CI

#67 fix(doc): flex loop doc
  docs/brainrot-user-guide.md
Labels: documentation

#65 feat: add support for arrays
  ast.c
  ast.h
  examples/bool_array.brainrot
  examples/char_array.brainrot
  examples/double_array.brainrot
  examples/float_array.brainrot
  examples/int_array.brainrot
  examples/short_array.brainrot
  lang.l
  lang.y
  tests/expected_results.json
Labels: enhancement

#71 refactor(parser): refactor expresstion and grammer
  ast.c
  ast.h
  lang.y
Labels: refactor

#72 Update README.md
  README.md
Labels: documentation

#74 docs: remove known issues from README
  README.md
Labels: documentation

#77 fix(array): memory leaks in ExpressionList
  ast.c
  lang.y
Labels: bugfix

#78 Introduce HashMap for Symbol Table Management
  .github/workflows/ci.yml
  Makefile
  ast.c
  ast.h
  hm.c
  lang.y
  test_cases/char_array.brainrot
Labels: refactor

#81 feat: custom memory management lib
  .github/workflows/ci.yml
  Makefile
  hm.c
  lib/hm.c
  lib/hm.h
  lib/mem.c
  lib/mem.h
Labels: enhancement, refactor

#82 use safe memory lib and add memory leaks checks to CI
  .github/workflows/ci.yml
  Makefile
  ast.c
  ast.h
  lang.y
  lib/hm.c
  lib/hm.h
  lib/mem.c
  lib/mem.h
Labels: enhancement, refactor

#85 Fix memory leaks
  .github/workflows/ci.yml
  ast.c
  ast.h
  lang.l
  lang.y
  lib/hm.c
  lib/mem.c
  lib/mem.h
  test_cases/division_by_zero.brainrot
  test_cases/division_edge_cases.brainrot
  tests/expected_results.json
Labels: enhancement, refactor, CI, tests, bugfix

#86 Several stuff
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  docs/the-brainrot-programming-language.md
  run_valgrind_tests.sh
Labels: documentation

#89 Introducing variable scope
  ast.c
  ast.h
  lang.y
  test_cases/array_initialization.brainrot
  test_cases/circle_area.brainrot
  test_cases/inc-dec.brainrot
  test_cases/int.brainrot
  test_cases/mixed_types.brainrot
  test_cases/uint.brainrot
  tests/expected_results.json
Labels: enhancement, refactor, bugfix

#92 docs: update readme with subreddit link
  README.md
Labels: documentation

#90 feat: user-defined functions
  ast.c
  ast.h
  lang.l
  lang.y
  test_cases/add_two_numbers.brainrot
  test_cases/is_prime.brainrot
  test_cases/max_gigachad.brainrot
  test_cases/mul_two_numbers.brainrot
  tests/expected_results.json
Labels: enhancement, help wanted

#94 docs: update limitations
  README.md
Labels: documentation

#104 docs: fix hello world example in README
  README.md
Labels: documentation

#109 add install and uninstall rules to makefile
  Makefile
  README.md
Labels: documentation, enhancement

#110 memory checks
  ast.c
  lang.y
  lib/mem.c
Labels: enhancement, refactor
