Repository Brainrotlang/brainrot, pull requests merged in 2025-02, with the labels that each got.

#108 Fix: add test cases for slorp
  ast.c
  lang.y
  lib/input.c
  run_valgrind_tests.sh
  test_cases/slorp_char.brainrot
  test_cases/slorp_double.brainrot
  test_cases/slorp_float.brainrot
  test_cases/slorp_int.brainrot
  test_cases/slorp_short.brainrot
  test_cases/slorp_string.brainrot
  tests/expected_results.json
  tests/test_brainrot.py
Labels: help wanted, tests, bugfix

#117 fix: compiler annoying warnings
  ast.c
  ast.h
  lang.y
  lib/hm.c
  lib/hm.h
  lib/mem.h
Labels: refactor

#118 Add `Werror` to compiler flags
  Makefile
Labels: enhancement, CI

#120 Fix function scope
  Makefile
  ast.c
  ast.h
  test_cases/fib.brainrot
  test_cases/func_scope.brainrot
  tests/expected_results.json
Labels: bugfix

#121 ci(memory_leaks): Fix CI valgrind check and resolve function memory leaks
  ast.c
  run_valgrind_tests.sh
Labels: CI, bugfix

#124 Feat(func): enable type modifer in user defined function
  ast.c
  ast.h
  lang.y
  run_valgrind_tests.sh
  test_cases/func-modifier.brainrot
  tests/expected_results.json
Labels: enhancement, CI, tests

#127 Fix(runtime): access null pointer
  ast.c
Labels: bugfix
